// set catalogs order
export default {
  mine: {
    model: {
      basic: {},
      important: {},
      routine: {},
    },
    me: {
      basic: {},
      真诚: {},
      美好: {},
      有主见: {},
      问题: {},
    },
    life: {
      basic: {},
      work: {},
      pleasure: {},
      knowledge: {},
      health: {},
      with: {},
    },
    knowledge: {
      basic: {},
      direction: {},
      source: {},
      comprehension: {},
      pleasure: {},
      record: {},
      memory: {},
    },
    things: {
      basic: {},
      考研: {},
      gamble: {},
    },
    我的世界: {
      我的世界: {},
    },
    draft: {},
  },
  math: {
    model: {},
    elementary: {
      concepts: {},
      symbols: {},
      'number system': {},
      arithmetic: {},
      polynomial: {},
      'coordinate system': {},
      'logarithm & exponent': {},
      vector: {},
      set: {},
      sequence: {},
      map: {},
      function: {},
      'basic elementary function': {},
      'trigonometric function': {},
      'hyperbolic function': {},
      geometry: {},
      'reasoning & proof': {},
    },
    calculus: {
      basic: {},
      limitation: {},
      derivative: {},
      differential: {},
      'indefinite integral': {},
      'definite integral': {},
      'differential equation': {},
    },
    'linear algebra': {
      basic: {},
      determinant: {},
      matrix: {},
      'elementary transformation': {},
      vector: {},
    },
    'probability statistics': {},
    statistics: {},
  },
  computer: {
    basic: {
    },
    algorithm: {
      basic: {},
      c: {},
      algorithm: {},
      'linear list': {},
      'stack & queue': {},
      string: {},
      'array & matrix & generalized list': {},
      tree: {},
      graph: {},
      sorting: {},
      searching: {},
      example: {},
      考研: {},
    },
    network: {},
    organization: {},
    OS: {},
    compiling: {},
    linux: {
      basic: {},
      command: {},
      shell: {},
    },
    windows: {},
    mac: {},
  },
  ML: {
    ML: {},
    DL: {},
  },
  programming: {
    basic: {
    },
    organization: {

    },
    'prog pattern': {
      OOP: {},
      AOP: {},
      functional: {},
      'event driven': {},
    },
    async: {
      async: {},
      distributed: {},
      'multiprocess & multithreading': {},
    },
    test: {

    },
    'source code': {

    },
  },
  design: {
    'design pattern': {
      basic: {},
      mvc: {},
    },
    'api design': {
      RESTful: {},
      GraphQL: {},
    },
    auth: {
      'OAuth2.0': {},
      OpenID: {},
      SAML: {},
      CAS: {},
    },
    architecture: {
      microservice: {},
    },
    workflow: {
      持续集成: {},
      TDD: {},
    },
    maintenance: {},
    'tech selection': {},
  },
  html: {
    html: {
      basic: {},
      advanced: {},
      grammar: {},
      text: {},
      skeleton: {},
      media: {},
      structure: {},
      link: {},
      head: {},
      'lib emmet': {},
    },
    css: {
      basic: {},
      advanced: {},
      grammar: {},
      selector: {},
      attribute: {},
      models: {},
      layout: {},
    },
    'css lib': {},
    BOM: {
      basic: {},
      window: {},
      location: {},
      history: {},
      navigator: {},
      screen: {},
      'client detection': {},
    },
    DOM: {
      basic: {},
      Node: {},
      Document: {},
      Element: {},
      Attr: {},
      Text: {},
      DocumentType: {},
      Comment: {},
      CDATASection: {},
      DocumentFragment: {},
      'handle table': {},
      'handle form': {},
      'handle frames': {},
      'handle css': {},
      'handle js': {},
    },
    event: {},
    'web api': {},
  },
  PL: {
    js: {
      basic: {},
      advanced: {},
      compile: {},
      language: {},
      variable: {},
      operator: {},
      statement: {},
      'data-type': {},
      'pt Number': {},
      'pt String': {},
      'pt Boolean': {},
      'pt Null Undefined': {},
      'pt Symbol': {},
      'rt Array': {},
      'rt Function': {},
      'rt Object': {},
      'OO prototype': {},
      'OO class': {},
      'OO decorator': {},
      'async basic': {},
      'async callback': {},
      'async Promise': {},
      'async Generator': {},
      'async async': {},
      Iterator: {},
      Proxy: {},
      Reflect: {},
      Error: {},
      module: {},
      'design pattern': {},
    },
    'js std lib': {
      Global: {},
    },
    'js lib': {
      
    },
    ts: {
      basic: {},
      'type basic': {},
      'type generic': {},
      'type advanced': {},
      'OO interface': {},
      'OO class': {},
      'OO decorator': {},
      'mod namespace': {},
      'mod module': {},
    },
    node: {
      basic: {},
      advanced: {},
    },
    'node lib': {},
    py: {
      advanced: {},
      compile: {},
      language: {},
      variable: {},
      operator: {},
      statement: {},
      'data type': {},
      'pt None': {},
      'pt Number': {},
      'pt Bool': {},
      'pt str': {},
      'rt list': {},
      'rt tuple': {},
      'rt dict': {},
      'rt set': {},
      'rt function': {},
      'rt class': {},
      exception: {},
      'OO class': {},
      iteration: {},
      async: {},
      module: {},
    },
    'py std lib': {
      basic: {},
    },
    'py lib': {
      'package management': {},
    },
    Java: {
      basic: {},
      advanced: {},
      compile: {},
      JVM: {},
      language: {},
      variable: {},
      operator: {},
      statement: {},
      'data type': {},
      boolean: {},
      char: {},
      number: {},
      class: {},
      interface: {},
      'class String': {},
      'class Array': {},
      'class Object': {},
      'class Collection': {},
      permission: {},
      exception: {},
      reflection: {},
      annotation: {},
      generic: {},
      module: {},
      'design pattern': {},
    },
    'Java std lib': {
    },
    'Java EE': {
      basic: {},
      'java web': {},
      servlet: {},
      jsp: {},
    },
    'Java lib': {
      maven: {},
      spring: {},
      'spring mvc': {},
      structs2: {},
      hibernate: {},
      Mybatis: {},
      JUnit: {},
      tomcat: {},
      jetty: {},
      lucence: {},
      netty: {},
      mina: {},
      log4j: {},
      'commons-log': {},
      slf4j: {},
      quartz: {},
      jasper: {},

    },
    C: {
      basic: {},
      advanced: {},
      compile: {},
      language: {},
      variable: {},
      operator: {},
      statement: {},
      'data type': {},
      'pt primitive': {},
      enum: {},
      void: {},
      'dt pointer': {},
      'dt array': {},
      'dt function': {},
      'dt struct': {},
      'dt union': {},
      exception: {},
      module: {},
    },
    'C std lib': {
      basic: {},
    },
    'C lib': {},
    'C++': {
      basic: {},
      advanced: {},
      compile: {},
      language: {},
      variable: {},
      operator: {},
      statement: {},
      'data type': {},
      'pt primitive': {},
      enum: {},
      void: {},
      'dt pointer': {},
      'dt reference': {},
      'dt array': {},
      'dt function': {},
      'dt struct': {},
      'dt union': {},
      'dt class': {},
      exception: {},
      namespace: {},
      'OO class': {},
      generic: {},
      template: {},
      module: {},
    },
    'C++ lib': {},
    'C++ std lib': {},
    markup: {},
  },
  database: {
    basic: {},
    mySQL: {
      basic: {},
      advanced: {},
      storage: {},
      SQL: {},
      transaction: {},
      integration: {},
    },
  },
  tools: {
    git: {
      'git basic': {},
      'git mechanism': {},
      'git command': {},
    },
    svn: {

    },
  },
  story: {},
  craft: {},
  languages: {
    English: {
      model: {},
    },
    Japanese: {},
  },
};
